server:
  port: 5050

spring:
  application:
    name: configuration
  devtools:
    add-properties: false
  profiles:
    active: git
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    consul:
      host: 127.0.0.1
      discovery:
        prefer-ip-address: true
        instanceId: ${spring.application.name}-service:${spring.application.instance_id:${random.value}}
    config:
      server:
        git:
          uri: git@github.com:db-space-project/service-config.git
          private_key_file: ~/.ssh/id_rsa
          passphrase: dododuck
          skipSslValidation: true
          default-label: main
          search-paths: dbconnection,organization,gateway
        encrypt:
          enabled: false # Disable the server-side decryption